# 01 - PhoBERT base model: 5-fold OOF + full-train refit (seeds 42, 131, 9998)

Loops `resolve_pipeline_seeds()` (override with `TM_RUN_SEEDS`). Each seed writes `artifacts/seeds/{seed}/probs/phobert_{oof,val,test}.npy` and `artifacts/seeds/{seed}/metrics/phobert.json`. A finished seed is skipped.

In [1]:
%pip install -q transformers datasets accelerate scikit-learn pandas numpy

In [2]:
import sys, os

REPO_ROOT = '/content/drive/MyDrive/thesis/topicmodeling'
TMP_ROOT = '/content/ensemble_tmp'

if 'google.colab' in sys.modules:
    from google.colab import drive
    if not os.path.ismount('/content/drive'):
        drive.mount('/content/drive')
    if REPO_ROOT not in sys.path:
        sys.path.insert(0, REPO_ROOT)
else:
    import pathlib
    LOCAL = pathlib.Path.cwd().resolve()
    while LOCAL.name != 'tm_research' and LOCAL.parent != LOCAL:
        LOCAL = LOCAL.parent
    sys.path.insert(0, str(LOCAL.parent))

from tm_research.ensemble.colab_setup import setup_colab
paths = setup_colab(repo_root=REPO_ROOT, tmp_root=TMP_ROOT)

Mounted at /content/drive
[utils_io] pulled 174 files: /content/drive/MyDrive/thesis/topicmodeling/tm_research/ensemble/artifacts -> /content/ensemble_tmp/artifacts
[colab_setup] is_colab=True
[colab_setup] repo_root=/content/drive/MyDrive/thesis/topicmodeling
[colab_setup] tmp_root=/content/ensemble_tmp (hf_cache/bert_work/lora_work)
[colab_setup] artifacts=/content/ensemble_tmp/artifacts
[colab_setup] persistent_artifacts=/content/drive/MyDrive/thesis/topicmodeling/tm_research/ensemble/artifacts
[colab_setup] HF_TOKEN: set

In [3]:
from tm_research.ensemble.utils_io import (
    load_splits, activate_seed_artifacts, reset_artifacts_root,
)
from tm_research.ensemble.bert_oof import BertOOFConfig, run_bert_oof
from tm_research.ensemble.multiseed import resolve_pipeline_seeds, seed_is_complete

train_df, val_df, test_df, label_map = load_splits()
print('train', train_df.shape, 'val', val_df.shape, 'test', test_df.shape)
print('classes', label_map.class_names)

train (10549, 2) val (686, 2) test (692, 2)
classes ['Anger', 'Disgust', 'Enjoyment', 'Fear', 'Other', 'Sadness', 'Surprise']

In [4]:
REQUIRED_RELATIVE_PATHS = (
    'probs/phobert_oof.npy',
    'probs/phobert_val.npy',
    'probs/phobert_test.npy',
    'metrics/phobert.json',
)

all_metrics = {}
for seed in resolve_pipeline_seeds():
    if seed_is_complete(seed, REQUIRED_RELATIVE_PATHS):
        print(f'skip seed {seed}')
        continue
    activate_seed_artifacts(seed)
    try:
        print(f'Using seed: {seed}')
        cfg = BertOOFConfig(
            model_name='vinai/phobert-base-v2',
            output_name='phobert',
            seed=seed,
            n_folds=3,
            num_epochs=20,
            learning_rate=2e-5,
            max_length=256,
            train_batch_size=128,
            eval_batch_size=256,
            grad_accum_steps=2,
            warmup_ratio=0.1,
            weight_decay=0.01,
            early_stopping_patience=3,
            lr_scheduler_type='cosine',
            max_grad_norm=1.0,
            work_dir=str(paths.bert_work / f'phobert_seed_{seed}'),
        )
        all_metrics[seed] = run_bert_oof(cfg, train_df, val_df, test_df, label_map)
    finally:
        reset_artifacts_root()
all_metrics

Using seed: 42
[phobert] running 3-fold OOF on N=10549

config.json:   0%|          | 0.00/678 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/895k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.13M [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  540MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7032 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  540MB

model.safetensors: downloading bytes:           |  0.00B

Map:   0%|          | 0/3517 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 1/3 acc=0.4160

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 2/3 acc=0.6590

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 3/3 acc=0.4187
[phobert] refitting on full train and predicting val/test

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/10549 [00:00<?, ? examples/s]

Map:   0%|          | 0/686 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/692 [00:00<?, ? examples/s]

[phobert] done in 8.4 min — oof=0.4979 val=0.6210 test=0.6329
Using seed: 131
[phobert] running 3-fold OOF on N=10549

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7032 [00:00<?, ? examples/s]

Map:   0%|          | 0/3517 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 1/3 acc=0.6005

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 2/3 acc=0.4044

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 3/3 acc=0.4534
[phobert] refitting on full train and predicting val/test

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/10549 [00:00<?, ? examples/s]

Map:   0%|          | 0/686 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/692 [00:00<?, ? examples/s]

[phobert] done in 7.7 min — oof=0.4861 val=0.6268 test=0.6460
Using seed: 9998
[phobert] running 3-fold OOF on N=10549

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7032 [00:00<?, ? examples/s]

Map:   0%|          | 0/3517 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 1/3 acc=0.6773

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 2/3 acc=0.6115

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/7033 [00:00<?, ? examples/s]

Map:   0%|          | 0/3516 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  fold 3/3 acc=0.3891
[phobert] refitting on full train and predicting val/test

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: vinai/phobert-base-v2
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/10549 [00:00<?, ? examples/s]

Map:   0%|          | 0/686 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Map:   0%|          | 0/692 [00:00<?, ? examples/s]

[phobert] done in 7.8 min — oof=0.5593 val=0.6122 test=0.6214

{42: {'model_name': 'vinai/phobert-base-v2',
  'output_name': 'phobert',
  'seed': 42,
  'n_folds': 3,
  'fold_val_accuracies': [0.415979528006824,
   0.6589874857792947,
   0.41865756541524457],
  'oof_accuracy': 0.4978670964072424,
  'oof_recall': 0.49744486403559207,
  'oof_f1': 0.46491021212651695,
  'oof_f1_weighted': 0.46526554773883716,
  'val_accuracy': 0.6209912536443148,
  'val_recall': 0.6341492666598467,
  'val_f1': 0.5925021015544649,
  'val_f1_weighted': 0.6230838465203326,
  'test_accuracy': 0.6329479768786127,
  'test_recall': 0.637039179891992,
  'test_f1': 0.6089476477037973,
  'test_f1_weighted': 0.6385856442849229,
  'num_train': 10549,
  'num_val': 686,
  'num_test': 692,
  'elapsed_seconds': 501.55177903175354,
  'tuning': {'learning_rate': 2e-05,
   'lr_scheduler_type': 'cosine',
   'warmup_ratio': 0.1,
   'weight_decay': 0.01,
   'num_epochs': 20,
   'train_batch_size': 128,
   'grad_accum_steps': 2,
   'max_length': 256,
   'early_stopping_patience': 3,
   'max_grad_norm': 1.0}},
 131: {'model_name': 'vinai/phobert-base-v2',
  'output_name': 'phobert',
  'seed': 131,
  'n_folds': 3,
  'fold_val_accuracies': [0.6005117998294001,
   0.4044368600682594,
   0.4533560864618885],
  'oof_accuracy': 0.4861124277182671,
  'oof_recall': 0.48627355808733164,
  'oof_f1': 0.4589938226884132,
  'oof_f1_weighted': 0.4590279802079726,
  'val_accuracy': 0.6268221574344023,
  'val_recall': 0.6066703071076017,
  'val_f1': 0.5828213505087911,
  'val_f1_weighted': 0.6270198116826474,
  'test_accuracy': 0.6459537572254336,
  'test_recall': 0.6278379349306675,
  'test_f1': 0.6160511836904885,
  'test_f1_weighted': 0.6476337548636112,
  'num_train': 10549,
  'num_val': 686,
  'num_test': 692,
  'elapsed_seconds': 461.66929364204407,
  'tuning': {'learning_rate': 2e-05,
   'lr_scheduler_type': 'cosine',
   'warmup_ratio': 0.1,
   'weight_decay': 0.01,
   'num_epochs': 20,
   'train_batch_size': 128,
   'grad_accum_steps': 2,
   'max_length': 256,
   'early_stopping_patience': 3,
   'max_grad_norm': 1.0}},
 9998: {'model_name': 'vinai/phobert-base-v2',
  'output_name': 'phobert',
  'seed': 9998,
  'n_folds': 3,
  'fold_val_accuracies': [0.6772817742394086,
   0.611490329920364,
   0.3890784982935154],
  'oof_accuracy': 0.5592947198786615,
  'oof_recall': 0.5591702493633213,
  'oof_f1': 0.5291005105174098,
  'oof_f1_weighted': 0.5295067383180245,
  'val_accuracy': 0.6122448979591837,
  'val_recall': 0.5864902545596117,
  'val_f1': 0.5763675617799289,
  'val_f1_weighted': 0.6135417058198139,
  'test_accuracy': 0.6213872832369942,
  'test_recall': 0.5963726416560916,
  'test_f1': 0.5910647508143326,
  'test_f1_weighted': 0.6227287896461687,
  'num_train': 10549,
  'num_val': 686,
  'num_test': 692,
  'elapsed_seconds': 468.16916394233704,
  'tuning': {'learning_rate': 2e-05,
   'lr_scheduler_type': 'cosine',
   'warmup_ratio': 0.1,
   'weight_decay': 0.01,
   'num_epochs': 20,
   'train_batch_size': 128,
   'grad_accum_steps': 2,
   'max_length': 256,
   'early_stopping_patience': 3,
   'max_grad_norm': 1.0}}}

In [5]:
from tm_research.ensemble.utils_io import push_artifacts_to_persistent
push_artifacts_to_persistent()

[utils_io] pushed 186 files: /content/ensemble_tmp/artifacts -> /content/drive/MyDrive/thesis/topicmodeling/tm_research/ensemble/artifacts

PosixPath('/content/drive/MyDrive/thesis/topicmodeling/tm_research/ensemble/artifacts')

In [6]:
from google.colab import runtime
runtime.unassign()